### ISSUE TITLE
Saved in the wrong order

### ISSUE THREAD

**Issue by PhillippOhlandt** [rossriley/bolt-extension-sortable-relations#1]
Hello,

I installed this extension because I want to save relations in a specific order. I have built my own contentfield for relation (with a little more functions).

First I tried just the standard select with your extension but it doesn't seem to work. Here a short video:
http://recordit.co/yiAIcoQdx0 

I saved before I reloaded the page and the entries are sent in the right order.

**Comment by PhillippOhlandt** [comment]
Looks like an output problem. The values in the DB are correct and in the right order based on the order column.

**Comment by PhillippOhlandt** [comment]
In your `_relationships.twig` template on line `27`:

```{% if relation.sortable|default(false) %}``` seems always false even when my relation block in the config looks like:

```
relations:
        books:
            multiple: true
            sortable: true
            label: Select books
```
